//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlashCards11
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudyAppItem
    {
        public int item_id { get; set; }
        public string item_name { get; set; }
        public string item_content { get; set; }
        public string item_subject { get; set; }
    }
}
