//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlashCards11
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class User : INotifyPropertyChanged

    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Session = new HashSet<Session>();
        }

      
        public int _userID;
     

        //public int User_ID { get; set; }
        public int User_ID
        {
            get { return _userID; }
            set
            {
                _userID = value;
                PropertyChanged?.Invoke(this, new PropertyChangedEventArgs("User_ID"));
            }
        }

        
        public string User_Name { get; set; }
        public string Hash { get; set; }
        public string Salt { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Session> Session { get; set; }

        public event PropertyChangedEventHandler PropertyChanged;


    
    }
}
